'use client';

export interface FlavorSwatch {
	id: string;
	name: string;
	hex: string;
	description: string;
}

export const FLAVOR_SWATCHES: FlavorSwatch[] = [
	{
		id: 'galactic-guava',
		name: 'Galactic Guava',
		hex: '#FF3E9E',
		description: 'Bold guava nectar infused with cosmic citrus sparks.',
	},
	{
		id: 'neon-lychee',
		name: 'Neon Lychee',
		hex: '#FF6CD9',
		description: 'Electric lychee sweetness with ultraviolet hibiscus glow.',
	},
	{
		id: 'stellar-papaya',
		name: 'Stellar Papaya',
		hex: '#FF8450',
		description: 'Juicy papaya sunrise with a dash of solar spice.',
	},
	{
		id: 'solar-mango',
		name: 'Solar Mango',
		hex: '#FFB347',
		description: 'Sun-drenched mango syrup kissed by comet caramel.',
	},
	{
		id: 'comet-apricot',
		name: 'Comet Apricot',
		hex: '#FFA366',
		description: 'Luminous apricot streaks trailing a sweet meteor tail.',
	},
	{
		id: 'lunar-tangerine',
		name: 'Lunar Tangerine',
		hex: '#FF792E',
		description: 'Vibrant tangerine zest orbiting around molten amber.',
	},
	{
		id: 'aurora-coral',
		name: 'Aurora Coral',
		hex: '#FF5A5C',
		description: 'Shimmering coral blaze forged in aurora waves.',
	},
	{
		id: 'plasma-persimmon',
		name: 'Plasma Persimmon',
		hex: '#FF7B4A',
		description: 'Persimmon plasma swirling with caramelized nova dust.',
	},
	{
		id: 'hypernova-honey',
		name: 'Hypernova Honey',
		hex: '#FFBD2C',
		description: 'Golden honey burst supercharged with citrus photons.',
	},
	{
		id: 'quantum-custard',
		name: 'Quantum Custard',
		hex: '#FFC94E',
		description: 'Vanilla custard folded through quantum lemon beams.',
	},
	{
		id: 'stardrop-pear',
		name: 'Stardrop Pear',
		hex: '#FFDE66',
		description: 'Glazed pear droplets drifting through stardust sugar.',
	},
	{
		id: 'orbit-lime',
		name: 'Orbit Lime',
		hex: '#CCFF3D',
		description: 'Neon lime comet with crystalline green apple ice.',
	},
	{
		id: 'cosmic-kiwi',
		name: 'Cosmic Kiwi',
		hex: '#9DFF57',
		description: 'Kiwi nebula laced with galactic spearmint mist.',
	},
	{
		id: 'nebula-melon',
		name: 'Nebula Melon',
		hex: '#7BFF72',
		description: 'Honeydew Stardrift swirled with cucumber starlight.',
	},
	{
		id: 'supernova-apple',
		name: 'Supernova Apple',
		hex: '#7CFF9E',
		description: 'Crisp apple explosion with shooting-star vanilla.',
	},
	{
		id: 'emerald-zen',
		name: 'Emerald Zen',
		hex: '#26EBA6',
		description: 'Matcha serenity drenched in jade citrus radiance.',
	},
	{
		id: 'ionic-menthol',
		name: 'Ionic Menthol',
		hex: '#15D0C1',
		description: 'Frosted menthol tides with ionic eucalyptus glimmer.',
	},
	{
		id: 'turquoise-tide',
		name: 'Turquoise Tide',
		hex: '#17C6E0',
		description: 'Tidal blue lagoon layered with candied sea salt foam.',
	},
	{
		id: 'aqua-laser',
		name: 'Aqua Laser',
		hex: '#00B5FF',
		description: 'Laser-blue bubble ice glazed with starfruit zest.',
	},
	{
		id: 'cerulean-twist',
		name: 'Cerulean Twist',
		hex: '#1E8CFF',
		description: 'Electric blueberry cyclone spun with citrus wind.',
	},
	{
		id: 'ultra-marine',
		name: 'Ultra Marine',
		hex: '#345DFF',
		description: 'Deep-sea blackberry tide infused with midnight vanilla.',
	},
	{
		id: 'indigo-nightfall',
		name: 'Indigo Nightfall',
		hex: '#4C3CFF',
		description: 'Indigo velvet dusk with starry plum reduction.',
	},
	{
		id: 'cosmic-blackcurrant',
		name: 'Cosmic Blackcurrant',
		hex: '#5A1EFF',
		description: 'Blackcurrant galaxies dusted with moonlit licorice.',
	},
	{
		id: 'violet-vortex',
		name: 'Violet Vortex',
		hex: '#7A00FF',
		description: 'Vortex of violet candied grapes and midnight orchids.',
	},
	{
		id: 'stellar-lavender',
		name: 'Stellar Lavender',
		hex: '#A45CFF',
		description: 'Lavender stardust whipped with vanilla nebula cream.',
	},
	{
		id: 'ultraviolet-berry',
		name: 'Ultraviolet Berry',
		hex: '#C246FF',
		description: 'Ultraviolet blackberry syrup and indigo sugar pearls.',
	},
	{
		id: 'nebula-rose',
		name: 'Nebula Rose',
		hex: '#EC52FF',
		description: 'Rose stardust clouds layered with lychee starlight.',
	},
	{
		id: 'prism-orchid',
		name: 'Prism Orchid',
		hex: '#FF69F9',
		description: 'Orchid candy prism spiked with crystalline dragonfruit.',
	},
	{
		id: 'ruby-quasar',
		name: 'Ruby Quasar',
		hex: '#FF2F7A',
		description: 'Ruby-toned quasar burst of raspberry comet foam.',
	},
	{
		id: 'crimson-pulse',
		name: 'Crimson Pulse',
		hex: '#FF0F45',
		description: 'Crimson pomegranate pulses wrapped in chili nebula.',
	},
	{
		id: 'meteor-mochi',
		name: 'Meteor Mochi',
		hex: '#FF6F91',
		description: 'Strawberry mochi meteors dusted with sakura sugar.',
	},
	{
		id: 'peach-aurora',
		name: 'Peach Aurora',
		hex: '#FF8AB6',
		description: 'Peach aurora sheets melting over vanilla stardust.',
	},
	{
		id: 'plasma-peony',
		name: 'Plasma Peony',
		hex: '#FF5FB8',
		description: 'Peony-infused plasma swirling with raspberry prism.',
	},
	{
		id: 'radiant-rhubarb',
		name: 'Radiant Rhubarb',
		hex: '#FF4C7D',
		description: 'Tart rhubarb blaze brightened with pink galaxy sugar.',
	},
	{
		id: 'ember-plum',
		name: 'Ember Plum',
		hex: '#D43D7A',
		description: 'Smoky plum embers drizzled in starlit cinnamon.',
	},
	{
		id: 'infrared-cherry',
		name: 'Infrared Cherry',
		hex: '#BF1A5C',
		description: 'Infrared cherry core fused with molten cola spice.',
	},
	{
		id: 'ember-espresso',
		name: 'Ember Espresso',
		hex: '#663A2A',
		description: 'Roasted espresso ember with toffee asteroid crumble.',
	},
	{
		id: 'mocha-meteorite',
		name: 'Mocha Meteorite',
		hex: '#7A4B33',
		description: 'Mocha meteorites glazed in caramel comet tails.',
	},
	{
		id: 'amber-ambergris',
		name: 'Amber Ambergris',
		hex: '#9E6A39',
		description: 'Spiced amber nectar swirling with oak stardust.',
	},
	{
		id: 'honeyed-halo',
		name: 'Honeyed Halo',
		hex: '#D99B3A',
		description: 'Golden halo honey infused with candied ginger sparks.',
	},
	{
		id: 'butterscotch-blaze',
		name: 'Butterscotch Blaze',
		hex: '#E6A44D',
		description: 'Butterscotch blaze raining in caramel meteor drips.',
	},
	{
		id: 'amber-cream',
		name: 'Amber Cream',
		hex: '#F2C37B',
		description: 'Velvet amber cream with vanilla cloud swirls.',
	},
	{
		id: 'coconut-comet',
		name: 'Coconut Comet',
		hex: '#F9E3C8',
		description: 'Coconut comet foam dusted with star-kissed sugar.',
	},
	{
		id: 'frosted-lyra',
		name: 'Frosted Lyra',
		hex: '#E8F7FF',
		description: 'Frosted lychee mist with starlight coconut frost.',
	},
	{
		id: 'glacier-orbit',
		name: 'Glacier Orbit',
		hex: '#C9F1FF',
		description: 'Icy blue glacier swirl shimmering with mint crystals.',
	},
	{
		id: 'ionized-mint',
		name: 'Ionized Mint',
		hex: '#9DF3D2',
		description: 'Ionized mint layers with chilled basil comets.',
	},
	{
		id: 'plasma-peppermint',
		name: 'Plasma Peppermint',
		hex: '#6DE1C6',
		description: 'Peppermint plasma ribbons with candied winter stardust.',
	},
	{
		id: 'celestial-cucumber',
		name: 'Celestial Cucumber',
		hex: '#72E7AE',
		description: 'Cucumber starlight tonic with jade lime nebulae.',
	},
	{
		id: 'zen-jade',
		name: 'Zen Jade',
		hex: '#55D69E',
		description: 'Jade matcha serenity bathed in sparkling lemongrass.',
	},
	{
		id: 'chartreuse-comet',
		name: 'Chartreuse Comet',
		hex: '#B4FF5D',
		description: 'Chartreuse comet trail streaked with candied citron.',
	},
	{
		id: 'acid-apple',
		name: 'Acid Apple',
		hex: '#D8FF57',
		description: 'Sour apple acid pop with neon lemon static.',
	},
	{
		id: 'stellar-marshmallow',
		name: 'Stellar Marshmallow',
		hex: '#F9DFFF',
		description: 'Stellar marshmallow fluff laced with raspberry quartz.',
	},
	{
		id: 'prismatic-rosewater',
		name: 'Prismatic Rosewater',
		hex: '#FFC2F9',
		description: 'Rosewater prisms refracting through lychee dew.',
	},
];
